const MODES=[['learn','◈','Concepts'],['questions','✎','Question bank'],['flashcards','▣','Flashcards'],['tests','◷','30-mark tests'],['quiz','✓','MCQ practice'],['resources','↗','References']];
const TESTS=[
 {title:'Matrix foundations',sub:'Rank, systems & eigenvectors',qs:['rank5','systems5','consistency10','eigen10']},
 {title:'Matrix methods',sub:'Inverses, dependence & matrix powers',qs:['inverse5','dependence5','rank10','cayley10']},
 {title:'Differentiation essentials',sub:'Chain rule, parameters & implicit curves',qs:['rules5','logarithmic5','parametric10','implicit10']},
 {title:'Calculus in action',sub:'Theorems, derivatives & optimization',qs:['rolle5','higher5','mvt10','extrema10']},
 {title:'Mixed revision A',sub:'A little algebra. A little calculus.',qs:['consistency5','parametric5','inverse10','higher10']},
 {title:'Mixed revision B',sub:'Connect ideas across both units',qs:['eigen5','extrema5','dependence10','rolle10']}
];
const ALL=TOPICS.flatMap(t=>t.questions.map(q=>({...q,topic:t.title,unit:t.unit})));
let difficulty='All',unit=0,mark=0,topicFilter='all',flashIndex=0,flipped=false,quizIndex=0,quizAnswers={},testRevealed=false,timer=null,remaining=45*60,activeTest=-1;
const main=document.getElementById('main');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function announce(s){document.getElementById('announce').textContent=s}
function intro(kicker,title,desc,tag='UNIT 01 + UNIT 02'){return `<div class="intro"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p>${desc}</p></div><span class="tag">${tag}</span></div>`}
function units(){return `<div class="tabs" aria-label="Unit filter">${[[0,'All topics'],[1,'Unit 1 · Matrices'],[2,'Unit 2 · Calculus']].map(([v,s])=>`<button data-unit="${v}" class="${unit===v?'selected':''}" aria-pressed="${unit===v}">${s}</button>`).join('')}</div>`}
function question(q,num='',test=false){return `<article class="question"><div class="question-header"><span class="marks ${q.marks===10?'ten':''}">${q.marks} MARKS</span><span class="difficulty ${q.difficulty?.toLowerCase()||'medium'}">${q.difficulty||'Medium'}</span><span class="origin">${q.origin||'Study-set practice'}</span><span>${num?`QUESTION ${num} · `:''}${esc(q.topic||'EXAM-STYLE PRACTICE')}</span></div><p>${esc(q.prompt)}</p>${test?`<label class="answer-label" for="answer-${q.id}">Your working (kept while this test is open)</label><textarea class="answer-area" id="answer-${q.id}" placeholder="Try it on paper, or jot your steps here."></textarea>`:''}<details ${test?'class="test-solution" hidden':''}><summary>See the worked solution</summary><ol class="steps">${q.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="mark-guide">${q.marks===5?'Suggested marking: method 1 · working 3 · conclusion 1.':'Suggested marking: setup and conditions 2 · main working 5 · conclusion and verification 3.'}</div></details></article>`}
function render(){const [mode='learn',id]=location.hash.slice(1).split('/');document.getElementById('nav').innerHTML=MODES.map(([m,i,l])=>`<a href="#${m}" class="${m===mode?'active':''}" ${m===mode?'aria-current="page"':''}><span class="nav-symbol">${i}</span>${l}</a>`).join('');document.getElementById('crumb').textContent=MODES.find(x=>x[0]===mode)?.[2]||'Concepts';
 if(mode!=='tests'&&timer){clearInterval(timer);timer=null}
 if(mode==='learn'&&id){renderLesson(id)}else if(mode==='learn'){renderLearn()}else if(mode==='questions'){renderQuestions()}else if(mode==='flashcards'){renderFlash()}else if(mode==='tests'){id===undefined?renderTests():renderTest(Number(id))}else if(mode==='quiz'){renderQuiz()}else if(mode==='resources'){renderResources()}else{location.hash='learn'}bind();}
function renderLearn(){const list=TOPICS.filter(t=>!unit||t.unit===unit);main.innerHTML=intro('LESS PANIC. MORE PRACTICE.','Make the maths click.','Pick a concept. Build your intuition. Put it to work.')+`<div class="banner"><div><h2>Your next exam, one idea at a time.</h2><p>Clear explanations, complete worked solutions, and a little space to figure it out yourself.</p><div class="stats"><span>15 topics</span><span>75 worked questions</span><span>6 × 30-mark tests</span></div></div><div class="formula-big">Av = λv<br>f′(x)</div></div><div class="section-head"><h2>Choose your starting point</h2>${units()}</div><div class="grid">${list.map((t,i)=>`<button class="topic-card" data-lesson="${t.id}"><div class="card-top"><span class="icon-box">${t.unit===1?'[ ]':'ƒ′'}</span><span class="tag">UNIT 0${t.unit}</span></div><h3>${esc(t.title)}</h3><p>${esc(t.idea.split('. ')[0])}.</p><div class="card-bottom"><span>Learn + practice</span><span aria-hidden="true">↗</span></div></button>`).join('')}</div>`}
function renderLesson(id){const t=TOPICS.find(x=>x.id===id);if(!t){location.hash='learn';return}main.innerHTML=`<button class="back" data-go="learn">← All concepts</button>`+intro(`UNIT 0${t.unit} / CONCEPT NOTES`,t.title,'Understand the idea before memorizing the method.')+`<div class="lesson-grid"><div><section class="panel"><h2>The idea, simply.</h2><p>${esc(t.idea)}</p><div class="formula">${esc(t.formula)}</div></section><h2 style="margin:27px 0 18px">Put it into practice</h2>${t.questions.map(q=>question({...q,topic:t.title})).join('')}</div><aside><div class="highlight"><h3>✦ Highlight this</h3><p>${esc(t.tip)}</p></div><div class="panel" style="margin-top:20px"><h3>Your study loop</h3><p class="muted">Read the idea once. Cover the solution. Try the question. Compare your first incorrect step.</p><button class="btn" data-topic-cards="${t.id}">Revise with flashcards ↗</button></div></aside></div>`}
function difficultyOptions(){return `<select id="difficulty-select" aria-label="Question difficulty">${['All','Easy','Medium','Hard'].map(d=>`<option ${difficulty===d?'selected':''} value="${d}">${d==='All'?'All difficulty levels':d}</option>`).join('')}</select>`}function renderQuestions(){let qs=ALL.filter(q=>(!unit||q.unit===unit)&&(!mark||q.marks===mark)&&(difficulty==='All'||q.difficulty===difficulty));main.innerHTML=intro('WORK IT OUT','The question bank.','75 worked questions, including 45 original challenges. Choose your difficulty and build up.')+`<div class="filters">${units()}${difficultyOptions()}<div class="tabs">${[0,5,10].map(m=>`<button data-mark="${m}" class="${mark===m?'selected':''}" aria-pressed="${mark===m}">${m?m+' marks':'All marks'}</button>`).join('')}</div></div><p class="meta-line">${qs.length} questions · Easy: direct application · Medium: combine methods · Hard: reasoning or multiple steps. Marks and difficulty are practice estimates.</p>`+qs.map((q,i)=>question(q,i+1)).join('')}
function cards(){return TOPICS.filter(t=>(!unit||t.unit===unit)&&(topicFilter==='all'||t.id===topicFilter)).flatMap(t=>[{topic:t.title,q:'What is the key idea behind '+t.title.toLowerCase()+'?',a:t.idea},{topic:t.title,q:'Recall the essential formula or rule.',a:t.formula},{topic:t.title,q:'What is the mistake to avoid?',a:t.tip}])}
function renderFlash(){let deck=cards();if(!deck.length){topicFilter='all';deck=cards()}flashIndex=((flashIndex%deck.length)+deck.length)%deck.length;const c=deck[flashIndex];main.innerHTML=intro('A LITTLE ACTIVE RECALL','Flip. Recall. Repeat.','Say the answer before you turn the card.')+`<div class="filters">${units()}<select aria-label="Flashcard topic" id="topic-select"><option value="all">Every topic</option>${TOPICS.filter(t=>!unit||t.unit===unit).map(t=>`<option value="${t.id}" ${topicFilter===t.id?'selected':''}>${esc(t.title)}</option>`).join('')}</select></div><div class="flash-wrap"><div class="section-head"><span class="meta-line">${esc(c.topic)}</span><span class="tag">${flashIndex+1} / ${deck.length}</span></div><button class="flash ${flipped?'flipped':''}" id="flip" aria-label="${flipped?'Show question':'Reveal answer'}"><small>${flipped?'THE ANSWER':'QUICK RECALL'}</small><h2>${esc(flipped?c.a:c.q)}</h2><p>${flipped?'Tap to see the question':'Tap to flip · think first'}</p></button><div class="flash-controls"><button class="btn light" id="prev-card">← Previous</button><button class="btn" id="next-card">Next card →</button></div><div class="dots"><span style="width:${(flashIndex+1)/deck.length*100}%"></span></div></div>`}
function renderTests(){main.innerHTML=intro('YOUR PRACTICE PAPERS','30 marks. You’ve got this.','Six focused tests. Each contains 2 × 5-mark + 2 × 10-mark questions.')+`<div class="notice">Suggested time: 45 minutes per test. Work on paper or type notes. Solutions stay hidden until you choose to review. Tests reuse selected question-bank problems.</div><div class="grid">${TESTS.map((t,i)=>`<article class="test-card"><div class="card-top"><span class="test-no">0${i+1}</span><span class="tag">30 MARKS</span></div><h3>${t.title}</h3><p>${t.sub}</p><div class="meta-line">4 questions · 45 min suggested</div><button class="btn ${i%3===0?'lime':''}" data-go="tests/${i}">Open test ↗</button></article>`).join('')}</div>`}
function renderTest(i){if(!TESTS[i]){location.hash='tests';return}if(timer){clearInterval(timer);timer=null}activeTest=i;remaining=45*60;testRevealed=false;const t=TESTS[i];main.innerHTML=`<button class="back" data-go="tests">← All practice tests</button>`+intro(`PRACTICE PAPER 0${i+1}`,t.title,'Attempt all four questions. Show your steps for partial credit.','30 MARKS')+`<div class="test-bar"><div><span class="number" id="clock">45:00</span><div style="font-size:12px">Optional timer · no automatic submission</div></div><div class="test-actions"><button class="btn lime" id="timer-toggle">Start timer</button><button class="btn light" id="review-test">Finish & review solutions</button></div></div><p class="meta-line">Working is temporary and is cleared if you leave or reload this test.</p>`+t.qs.map((id,n)=>question(ALL.find(q=>q.id===id),n+1,true)).join('')+`<div id="review-note" hidden class="highlight"><h3>Review your reasoning</h3><p>Open each worked solution and award marks using its guide. Typed answers are not automatically graded.</p></div>`}
function renderQuiz(){const deck=TOPICS.filter(t=>!unit||t.unit===unit);quizIndex=((quizIndex%deck.length)+deck.length)%deck.length;const t=deck[quizIndex],q=t.mcq,a=quizAnswers[t.id];main.innerHTML=intro('CHECK YOUR INSTINCTS','One question. One clear idea.','Choose an answer to see the reasoning immediately.')+`<div class="filters">${units()}<span class="tag">${quizIndex+1} / ${deck.length}</span></div><div class="panel" style="max-width:850px"><p class="eyebrow">${esc(t.title)}</p><h2 style="margin:15px 0 25px;line-height:1.4">${esc(q.q)}</h2><div class="quiz-options">${q.options.map((o,i)=>`<button class="option ${a!==undefined?(i===q.answer?'correct':i===a?'wrong':''):''}" data-option="${i}" data-qid="${t.id}" ${a!==undefined?'disabled':''}>${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div>${a!==undefined?`<div class="feedback" role="status"><b>${a===q.answer?'Correct.':'Let’s check that.'}</b> ${esc(q.explain)}</div>`:''}<div class="flash-controls"><button class="btn light" id="quiz-prev">← Previous</button><button class="btn" id="quiz-next">Next question →</button></div><button class="back" id="quiz-reset" style="margin:20px 0 0">Reset MCQ answers</button></div>`}
function renderResources(){main.innerHTML=intro('KEEP YOUR SOURCES CLOSE','Your reference shelf.','The links you shared, organized by unit.')+`<div class="notice">These six pages could not be retrieved during creation. They are provided as reference links; this site does not claim to reproduce their question banks. Explanations and solutions are independently written from the topics and readable materials discussed in your study session.</div><div class="resource-list">${[1,2].flatMap(u=>['notes','subjective','mcq'].map(k=>`<a href="https://notes.lpuverto.xyz/Sem1/MTH165/Unit${u}/${k}" target="_blank" rel="noopener noreferrer"><span class="eyebrow">UNIT 0${u}</span><h3>${{notes:'Notes & explanations',subjective:'Subjective questions',mcq:'Multiple-choice questions'}[k]} ↗</h3><span class="meta-line">notes.lpuverto.xyz · opens in a new tab</span></a>`)).join('')}</div><section class="panel" style="margin-top:25px"><h2>About this study set</h2><p>Core coverage follows your eight-topic revision list, with standard, implicit and logarithmic differentiation, matrix inverses, dependence and Cayley–Hamilton added from the readable sheets.</p><p class="muted">Reviewed material: Matrix_questions_260830_114106.pdf and tutorial sheet unit 21.pdf. The other matrix PDF was empty. Questions are exam-style; mark allocations and timing are suggestions.</p><div class="highlight"><h3>Corrections incorporated</h3><p>For x+y+z=6, 2x+y+5z=10, x+2y+λz=μ, the infinite-solution case is λ=6, μ=8. For λ=2, μ=8, the solution is (4,2,0). The inverse example is also corrected and verified by multiplication.</p></div></section>`}
function bind(){const df=document.getElementById('difficulty-select');if(df)df.onchange=()=>{difficulty=df.value;render()};main.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>{unit=+b.dataset.unit;topicFilter='all';flashIndex=0;flipped=false;quizIndex=0;render()});main.querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>{mark=+b.dataset.mark;render()});main.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.go);main.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>location.hash='learn/'+b.dataset.lesson);main.querySelectorAll('[data-topic-cards]').forEach(b=>b.onclick=()=>{unit=0;topicFilter=b.dataset.topicCards;flashIndex=0;flipped=false;location.hash='flashcards'});
 const on=(id,fn)=>{const e=document.getElementById(id);if(e)e.onclick=fn};on('flip',()=>{flipped=!flipped;render();document.getElementById('flip').focus()});on('prev-card',()=>{flashIndex--;flipped=false;render()});on('next-card',()=>{flashIndex++;flipped=false;render()});const sel=document.getElementById('topic-select');if(sel)sel.onchange=()=>{topicFilter=sel.value;flashIndex=0;flipped=false;render()};on('quiz-prev',()=>{quizIndex--;render()});on('quiz-next',()=>{quizIndex++;render()});on('quiz-reset',()=>{quizAnswers={};render()});main.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{quizAnswers[b.dataset.qid]=+b.dataset.option;render()});
 on('timer-toggle',()=>{const b=document.getElementById('timer-toggle');if(timer){clearInterval(timer);timer=null;b.textContent='Resume timer';return}if(remaining===0){remaining=2700}b.textContent='Pause timer';timer=setInterval(()=>{remaining--;document.getElementById('clock').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');if(remaining<=0){clearInterval(timer);timer=null;b.textContent='Restart timer';announce('Time is up. You can continue working or review your solutions.')}},1000)});
 on('review-test',()=>{if(timer){clearInterval(timer);timer=null}document.getElementById('timer-toggle').textContent='Resume timer';document.querySelectorAll('.test-solution').forEach(d=>d.hidden=false);document.getElementById('review-note').hidden=false;document.getElementById('review-test').textContent='Solutions unlocked';document.getElementById('review-test').disabled=true;announce('Solutions unlocked. Expand each solution to review your work.')});}
window.addEventListener('hashchange',()=>{window.scrollTo(0,0);render()});render();
